#!/usr/bin/env python3
"""Single-project OSS-Fuzz sweep with K2 routing + embargoed-repo auto-upload.

Per project (e.g. libpng), this script:

1. Resolves project metadata from google/oss-fuzz/projects/<name>/project.yaml
   (only ``main_repo`` is required; everything else is metadata for the report).
2. Clones / fast-forwards the source repo under ``--corpus-root``.
3. Invokes ``python -m bmc_agent.cli verify-dir`` on the source directory.
   Env vars sourced from ``~/.config/bmc-agent/env`` route cheap roles to K2.
4. Walks the produced ``bug_report.json`` files, keeps the ones that pass the
   full triage gate (confidence ∈ {confirmed_dynamic, confirmed_system_entry,
   confirmed_bmc} AND realism_check.verdict == "realistic"), renders a
   per-bug markdown report, and (unless ``--dry-run``) stages + commits +
   pushes them to the embargoed repo under
   ``findings/oss-fuzz/<project>/sweeps/<run-id>/audit/``.

This script does NOT touch CBMC config — it relies on the project's source
being self-contained enough for the existing pipeline. Multi-file projects
that need ``-I`` paths (libxml2, large codebases) will need to wire those
through ``--include-dir`` flags; for the libpng / expat / zstd starter
rotation a single source tree is usually enough.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Optional

PROJECT_YAML_URL = (
    "https://raw.githubusercontent.com/google/oss-fuzz/master/projects/{name}/project.yaml"
)
DEFAULT_CORPUS_ROOT = Path("/tmp/oss_fuzz_corpora")
DEFAULT_EMBARGOED_ROOT = Path("/tmp/aprover-findings-embargoed")
DEFAULT_ARTIFACT_ROOT = Path("/tmp/oss_fuzz_artifacts")

CONFIRMED_TIERS = {"confirmed_dynamic", "confirmed_system_entry", "confirmed_bmc"}


@dataclass
class ProjectMeta:
    name: str
    main_repo: str
    language: str
    homepage: str
    primary_contact: str

    @classmethod
    def fetch(cls, name: str) -> "ProjectMeta":
        url = PROJECT_YAML_URL.format(name=name)
        with urllib.request.urlopen(url, timeout=20) as resp:
            body = resp.read().decode("utf-8")
        meta = {"language": "", "homepage": "", "primary_contact": "", "main_repo": ""}
        for line in body.splitlines():
            line = line.strip()
            for key in meta:
                prefix = f"{key}:"
                if line.startswith(prefix):
                    value = line[len(prefix):].strip().strip("'\"")
                    meta[key] = value
        if not meta["main_repo"]:
            raise SystemExit(f"OSS-Fuzz {name}: project.yaml is missing main_repo")
        return cls(name=name, **meta)


def _run(cmd: list[str], *, cwd: Optional[Path] = None, check: bool = True,
         env: Optional[dict] = None, capture: bool = False) -> subprocess.CompletedProcess:
    """Wrapper around subprocess.run with sane defaults."""
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        check=check,
        env=env,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
        text=True,
    )


def clone_or_pull(meta: ProjectMeta, corpus_root: Path) -> Path:
    """Clone main_repo (shallow) or fast-forward an existing checkout.

    Returns the path to the working tree.
    """
    target = corpus_root / meta.name
    if target.exists() and (target / ".git").exists():
        try:
            _run(["git", "fetch", "--depth=1", "origin"], cwd=target)
            _run(["git", "reset", "--hard", "FETCH_HEAD"], cwd=target)
        except subprocess.CalledProcessError:
            # If fast-forward fails, fall back to a fresh clone next run.
            pass
        return target
    corpus_root.mkdir(parents=True, exist_ok=True)
    _run(["git", "clone", "--depth=1", meta.main_repo, str(target)])
    return target


def prepare_corpus(project_name: str, project_root: Path) -> None:
    """Run per-project build-prep steps required for `cc -E` to succeed.

    Many OSS-Fuzz C projects rely on autogenerated config headers that
    would normally be produced by ``./configure`` or CMake. For each
    starter-rotation project we ship the shortest-path equivalent here
    so the BMC-Agent pipeline can preprocess the sources without
    invoking the full build system.
    """
    if project_name == "libpng":
        # libpng requires pnglibconf.h (normally generated by ./configure
        # or copied from scripts/pnglibconf/* via the Makefile). It also
        # ships a generic prebuilt config in the repo root; use that.
        # We also disable PNG_TARGET_SPECIFIC_CODE_SUPPORTED so pngtarget.h
        # doesn't chase arm/intel/mips/powerpc subdirs that aren't in our
        # corpus tree — those gate platform-specific SIMD which BMC won't
        # exercise anyway.
        prebuilt = project_root / "pnglibconf.h.prebuilt"
        target = project_root / "pnglibconf.h"
        if prebuilt.exists() and not target.exists():
            text = prebuilt.read_text()
            text = text.replace(
                "#define PNG_TARGET_SPECIFIC_CODE_SUPPORTED",
                "/* #undef PNG_TARGET_SPECIFIC_CODE_SUPPORTED  (bmc-agent corpus) */",
            )
            target.write_text(text)
            print(f"[oss_fuzz_sweep] libpng: synthesized pnglibconf.h (no SIMD)")
        # Nuke the test / utility / contrib subdirs so verify-dir's
        # source discovery cannot pick them up. These contain test
        # programs (readpng2.c, etc.), CLI utilities (pngfix, pngcp),
        # and arch-specific shim files that explode the symbol space.
        # We also remove standalone test/utility .c files at the root.
        import shutil
        for noise in [
            "contrib", "tests",
            # Architecture-specific SIMD subdirs — bmc-agent's source
            # discovery walks into them; each has its own .c files
            # implementing the per-arch hooks. CBMC verifies them safe
            # trivially, no value to sweep.
            "arm", "intel", "mips", "powerpc", "loongarch", "riscv",
            # Build / metadata subdirs that may also contain .c.
            "ci", "scripts", "projects", "manuals", "LICENSES",
        ]:
            d = project_root / noise
            if d.exists():
                shutil.rmtree(d, ignore_errors=True)
                print(f"[oss_fuzz_sweep] libpng: removed {noise}/")
        for noise_c in [
            "example.c", "pngtest.c", "makepng.c", "pngsimd.c",
            "pnggetset.c", "pngvalid.c", "pngstest.c", "pngimage.c",
            "pngcp.c", "pngfix.c",
        ]:
            p = project_root / noise_c
            if p.exists():
                p.unlink()
                print(f"[oss_fuzz_sweep] libpng: removed {noise_c}")
    elif project_name == "libtiff":
        # libtiff: ship a minimal tif_config.h / tiffconf.h via cmake or
        # copy from the bundled templates. Both live under libtiff/.
        import re
        for tmpl, dest in [
            ("tif_config.h.cmake.in", "tif_config.h"),
            ("tiffconf.h.cmake.in", "tiffconf.h"),
            ("tiffvers.h.cmake.in", "tiffvers.h"),
        ]:
            src = project_root / "libtiff" / tmpl
            dst = project_root / "libtiff" / dest
            if src.exists():
                text = src.read_text()
                # #cmakedefine01 FOO  -> #define FOO 1
                text = re.sub(r"^#cmakedefine01\s+(\S+).*$",
                              r"#define \1 1", text, flags=re.M)
                # #cmakedefine FOO @VAR@  -> /* (left out) */
                text = re.sub(r"^#cmakedefine\s+(\S+)\s+.*$",
                              r"/* #define \1 (omitted) */", text, flags=re.M)
                # #cmakedefine FOO  -> #define FOO 1 for the safe defaults
                for tok in ("HAVE_FCNTL_H", "HAVE_STRINGS_H",
                            "HAVE_SYS_TYPES_H", "HAVE_UNISTD_H",
                            "HAVE_STRING_H", "HAVE_STDLIB_H"):
                    text = re.sub(rf"^#cmakedefine\s+{tok}\s*$",
                                  f"#define {tok} 1", text, flags=re.M)
                # Anything remaining: comment out
                text = re.sub(r"^#cmakedefine\s+",
                              "// #cmakedefine ", text, flags=re.M)
                # @VAR@ substitutions -> safe defaults
                text = text.replace("@TIFF_INT8_FORMAT@", "\"%hhd\"")
                text = text.replace("@TIFF_UINT8_FORMAT@", "\"%hhu\"")
                text = text.replace("@TIFF_INT16_FORMAT@", "\"%hd\"")
                text = text.replace("@TIFF_UINT16_FORMAT@", "\"%hu\"")
                text = text.replace("@TIFF_INT32_FORMAT@", "\"%d\"")
                text = text.replace("@TIFF_UINT32_FORMAT@", "\"%u\"")
                text = text.replace("@TIFF_INT64_FORMAT@", "\"%lld\"")
                text = text.replace("@TIFF_UINT64_FORMAT@", "\"%llu\"")
                # Size-of types — we run on x86_64 Linux, all 64-bit.
                for sz_key in ("SIZEOF_SIZE_T", "SIZEOF_VOIDP",
                               "SIZEOF_UNSIGNED_LONG", "SIZEOF_LONG"):
                    text = text.replace(f"@{sz_key}@", "8")
                for sz_key in ("SIZEOF_INT", "SIZEOF_UNSIGNED_INT"):
                    text = text.replace(f"@{sz_key}@", "4")
                # Catch-all for any other @VAR@ left
                text = re.sub(r"@[A-Z_]+@", "0", text)
                dst.write_text(text)
                print(f"[oss_fuzz_sweep] libtiff: synthesized {dest}")
    elif project_name == "expat":
        # expat: expat_config.h is autoconf-generated. Use the bundled
        # static defaults from expat/conftools/ if available.
        src = project_root / "expat" / "expat_config.h.in"
        dst = project_root / "expat" / "lib" / "expat_config.h"
        if src.exists() and not dst.exists():
            text = src.read_text()
            # Remove @VAR@ substitutions; we just need the file to exist.
            text = text.replace("/* #undef ", "// #undef ").replace("#undef ", "// #undef ")
            dst.write_text(text)
            print(f"[oss_fuzz_sweep] expat: synthesized expat_config.h")
    elif project_name == "zstd":
        # zstd: headers are inline, no autogen needed for the lib/ tree.
        pass
    # Else: unknown project — let the smoke test surface what's missing.


# Per-project file filters. The key files we want to sweep are the
# library's actual public-API implementation; OSS-Fuzz projects also
# ship test harnesses, CLI utilities, and code generators that produce
# spec-gen / harness-gen noise because their public API isn't what
# downstream users call.
EXCLUDE_PATTERNS: dict[str, list[str]] = {
    "libpng": [
        "example.c",       # canonical library-usage example
        "pngtest.c",       # libpng's own regression test
        "makepng.c",       # PNG generator utility (test fixtures)
        "pngsimd.c",       # SIMD dispatcher with target-specific code
        "pnggetset.c",     # not a real source file — sketched stub
        "pngvalid.c",      # validation test program
        "pngstest.c",      # secondary test program
        "pngimage.c",      # image conversion CLI
        "pngcp.c",         # PNG copy utility
        "pngfix.c",        # PNG repair utility
        "contrib/*",
    ],
    "libtiff": [
        "tools/*",         # CLI utilities (tiffcp, tiff2pdf, etc.)
        "test/*",
        "tif_predict.c",   # uses runtime function pointers; harness gen
                           # produces parse errors on the dispatch table
    ],
    "expat": [
        "tests/*",
        "xmlwf/*",         # CLI utility
        "examples/*",
    ],
    "zstd": [
        "programs/*",      # CLI (zstd, zstdcli)
        "tests/*",
        "contrib/*",
        "lib/legacy/*",    # older format-compat code; OSS-Fuzz doesn't
                           # treat these as primary targets
    ],
}


def discover_sources(project_root: Path) -> Path:
    """Pick the directory that holds the .c sources we want to sweep.

    libpng: png*.c sits in the repo root.
    libtiff: libtiff/tif_*.c
    expat: expat/lib/*.c
    zstd: lib/**/*.c (multi-dir; this script's first cut points at lib/)

    Returns the directory bmc-agent should sweep.
    """
    candidates = [
        project_root / "libtiff",                  # libtiff layout
        project_root / "expat" / "lib",            # expat layout
        project_root / "lib" / "decompress",       # zstd: the parser side (attack surface)
        project_root / "lib" / "common",           # zstd common (fallback)
        project_root / "lib",                      # generic
        project_root / "src",
        project_root,                              # libpng layout — last so subdirs win
    ]
    for cand in candidates:
        if cand.is_dir() and any(cand.glob("*.c")):
            return cand
    raise SystemExit(
        f"OSS-Fuzz {project_root.name}: no .c sources discovered in known layouts"
    )


def excludes_for(project_name: str) -> list[str]:
    """Return the source-file glob patterns to skip during verify-dir."""
    return EXCLUDE_PATTERNS.get(project_name, [])


def load_env_file(path: Path) -> dict[str, str]:
    """Source a bash-style ``export FOO=bar`` file into a dict."""
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for raw in path.read_text().splitlines():
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("export "):
            s = s[len("export "):]
        if "=" not in s:
            continue
        k, v = s.split("=", 1)
        v = v.strip()
        if (v.startswith("'") and v.endswith("'")) or (
            v.startswith('"') and v.endswith('"')
        ):
            v = v[1:-1]
        out[k.strip()] = v
    return out


def run_verify_dir(
    source_dir: Path,
    artifact_dir: Path,
    extra_env: dict[str, str],
    log_path: Path,
    *,
    minimal: bool = False,
    extra_args: Optional[list[str]] = None,
) -> int:
    """Invoke ``python -m bmc_agent.cli verify-dir`` on ``source_dir``.

    Returns the process exit code. Output is streamed to ``log_path``.
    """
    artifact_dir.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env.update(extra_env)

    cmd = [
        "uv", "run", "python", "-m", "bmc_agent.cli", "verify-dir",
        "--source-dir", str(source_dir),
        "--driver", "ossfz",
        "--output", str(artifact_dir),
        "--enable-realism-check",
        "--enable-dynamic-validation",
        # OPTION 3 (K2-only): disable tool-use code paths. K2 Think does
        # not support OpenAI-format tool_calls, so we route every role
        # to K2 (see ~/.config/bmc-agent/env) and skip the tool-use
        # agents. Tradeoff: lose the in-pipeline G1-G5 triage audit;
        # rely on realism + dyn-val for FP filtering. Manual re-audit
        # of the audit list is the same workflow used for postfix9c.
        "--no-realism-tools",
        "--no-spec-gen-tools",
        "--no-phase-3e-triage",
        # K2's responses don't reliably parse as the JSON format the v2
        # spec generator expects (observed 100% parse-fail in the first
        # libpng iteration). The legacy template-based spec generator
        # doesn't need an LLM at all — harness quality goes up.
        "--legacy-spec-gen",
    ]
    # Skip test / utility files for the current project (set by caller).
    for pat in extra_env.pop("__BMC_AGENT_EXCLUDE_PATS__", "").split("|"):
        if pat:
            cmd.extend(["--exclude", pat])
    # Add include directories: just the source dir itself + any
    # *direct* subdir of the project root that holds public headers.
    # We DO NOT rglob the whole tree because OSS-Fuzz projects' contrib/,
    # tests/, and arch-specific subdirs pollute the symbol space and
    # cause spec-gen to discover non-library functions (e.g. libpng's
    # contrib/gregbook/readpng2.c was being processed via the wide
    # include scan). The per-project corpus_prep should have already
    # placed any required generated headers in the source dir.
    cmd.extend(["--include-dir", str(source_dir)])
    # One sibling of source_dir as a header location, max — for
    # libtiff (libtiff/) and expat (expat/lib/) the source_dir IS the
    # subdir; for libpng / zstd source_dir IS the project root.
    parent_root = source_dir.parent if source_dir.parent != source_dir else source_dir
    for subdir in sorted(parent_root.iterdir()) if parent_root.is_dir() else []:
        if subdir == source_dir or not subdir.is_dir():
            continue
        # Only direct subdirs whose name suggests headers/config.
        if subdir.name in {"include", "config", "build"}:
            if any(subdir.glob("*.h")):
                cmd.extend(["--include-dir", str(subdir)])
    if minimal:
        cmd.append("--minimal")
    if extra_args:
        cmd.extend(extra_args)

    log_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"[oss_fuzz_sweep] launching: {' '.join(cmd)}")
    print(f"[oss_fuzz_sweep] log: {log_path}")
    with log_path.open("w") as fh:
        return subprocess.call(cmd, env=env, stdout=fh, stderr=subprocess.STDOUT)


def iter_bug_reports(artifact_dir: Path) -> Iterable[tuple[Path, dict]]:
    """Walk per-CEx bug reports under ``artifact_dir``.

    bmc-agent writes TWO levels of report:

      <fn>/bug_report.json          — CBMC-stage summary, NO confidence /
                                      realism / triage. Only 6 fields.
      <fn>/bug_reports/<name>.json  — per-CEx detailed report AFTER realism
                                      + dynamic + confidence stages. THIS is
                                      what we want for the triage gate.

    The per-CEx schema (observed 2026-05-29):
      {
        "saved_at": "...",
        "report": {
          "function_name": "...",
          "driver_name": "...",
          "bug_type": "...",
          "violated_property": "...",
          "counterexample": {...},
          "call_chain": [...],
          "confidence": "confirmed_dynamic|...|likely|unlikely|null",
          "realism_check": {"verdict": "realistic|unrealistic|uncertain", "reasoning": "..."},
          "cex_outcome": "...",
          "dynamic_outcome": "...",
          "dynamic_signal": "..."
        }
      }
    """
    for path in artifact_dir.rglob("bug_reports/*.json"):
        try:
            data = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        payload = data.get("report") if isinstance(data, dict) else None
        if not isinstance(payload, dict):
            continue
        yield path, payload


def passes_triage(report: dict) -> bool:
    """Apply the triage gate.

    Per-CEx report (from bug_reports/<name>.json) is keyed differently
    than the CBMC-stage bug_report.json: there's no `verified` field,
    just a `counterexample` (singular). The pipeline only writes these
    AFTER realism + dynamic + confidence stages run.

    Keep a bug iff:
      * confidence ∈ confirmed_* tiers
      * realism_check verdict is "realistic" OR is "uncertain" because of
        an LLM-error (which happens under K2 rate-limiting and shouldn't
        suppress real findings)
    """
    confidence = report.get("confidence", "")
    if confidence not in CONFIRMED_TIERS:
        return False
    realism = report.get("realism_check") or {}
    verdict = (realism.get("verdict") or "").lower()
    if verdict == "realistic":
        return True
    if verdict == "uncertain":
        reasoning = (realism.get("reasoning") or "").lower()
        # An "uncertain" verdict caused by an LLM transport error
        # (HTTP 429, network) is not a confidence-bearing rejection —
        # surface it for manual audit rather than silently dropping.
        if "llm call failed" in reasoning or "http 429" in reasoning or "llmerror" in reasoning:
            return True
    return False


def render_finding(report: dict, source_path: Path, run_id: str, meta: ProjectMeta) -> str:
    """Render a minimal but human-reviewable markdown finding from a per-CEx report."""
    fn = report.get("function_name", "<unknown>")
    # Per-CEx schema uses singular "counterexample" + "violated_property"
    cex = report.get("counterexample") or {}
    cprop = report.get("violated_property") or cex.get("property") or "<unknown>"
    conf = report.get("confidence", "<unknown>")
    realism = report.get("realism_check") or {}
    realism_verdict = realism.get("verdict", "")
    realism_reasoning = realism.get("reasoning", "")
    triage = report.get("triage", {}) or report.get("triage_result", {}) or {}
    triage_verdict = triage.get("verdict", "")
    triage_reasoning = triage.get("reasoning", "")

    return f"""# {meta.name}: {fn} — {cprop}

**Project**: {meta.name} ({meta.homepage})
**Upstream repo**: {meta.main_repo}
**Sweep run**: {run_id}
**Bug-report source**: `{source_path.name}`
**Confidence tier**: `{conf}`
**Realism verdict**: `{realism_verdict}`
**Triage verdict**: `{triage_verdict}`

## CBMC property
```
{cprop}
```

## Function under test
`{fn}`

## Realism check reasoning
{realism_reasoning or "_(not recorded)_"}

## Triage reasoning
{triage_reasoning or "_(not recorded)_"}

## Disclosure status
- ⏳ Upstream-status verification needed against shipping {meta.name} release.
- ⏳ Crafted reproducer / ASan witness pending.
- Primary OSS-Fuzz contact: {meta.primary_contact or "(see project.yaml)"}

## Raw report
See `{source_path}` in the artifact tree for the full JSON.
"""


def upload_findings(
    findings: list[tuple[Path, dict, str]],
    meta: ProjectMeta,
    run_id: str,
    embargoed_root: Path,
    dry_run: bool,
) -> Path:
    """Write per-bug markdown reports to the embargoed repo and (optionally) commit + push."""
    sweep_dir = embargoed_root / "findings" / "oss-fuzz" / meta.name / "sweeps" / run_id / "audit"
    sweep_dir.mkdir(parents=True, exist_ok=True)

    summary_lines = [
        f"# {meta.name} sweep {run_id} — summary",
        "",
        f"- Upstream: {meta.main_repo}",
        f"- Run UTC: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"- Confirmed+realistic findings: **{len(findings)}**",
        "",
    ]
    if not findings:
        summary_lines.append("_No bugs passed the triage gate this run._")
    else:
        summary_lines.append("| # | Function | Property | Confidence | Realism |")
        summary_lines.append("|---|---|---|---|---|")

    for i, (src_path, report, md) in enumerate(findings, start=1):
        fn = report.get("function", "<unknown>")
        safe_fn = "".join(c if c.isalnum() or c in "_-" else "_" for c in fn)
        safe_prop = "".join(c if c.isalnum() or c in "_-" else "_" for c in report.get("cbmc_property", ""))
        out_path = sweep_dir / f"{i:02d}_{safe_fn}_{safe_prop[:40]}.md"
        out_path.write_text(md)
        summary_lines.append(
            f"| {i} | `{fn}` | `{report.get('cbmc_property','')}` | "
            f"`{report.get('confidence','')}` | "
            f"`{(report.get('realism_check') or {}).get('verdict','')}` |"
        )

    summary_path = sweep_dir.parent / "SWEEP_SUMMARY.md"
    summary_path.write_text("\n".join(summary_lines) + "\n")

    if dry_run:
        print(f"[oss_fuzz_sweep] DRY RUN — would have committed {len(findings)} finding(s) and the SWEEP_SUMMARY.md")
        return sweep_dir

    _run(["git", "add", "-A"], cwd=embargoed_root)
    status = _run(["git", "status", "--short"], cwd=embargoed_root, capture=True)
    if not status.stdout.strip():
        print("[oss_fuzz_sweep] no changes to commit")
        return sweep_dir
    commit_msg = (
        f"oss-fuzz/{meta.name}: sweep {run_id} — {len(findings)} confirmed+realistic finding(s)\n\n"
        f"Auto-uploaded by tools/oss_fuzz_sweep.py.\n"
        f"Triage gate: confidence ∈ confirmed_* AND realism=realistic.\n"
        f"Upstream-status verification pending for each finding.\n"
    )
    _run(["git", "commit", "-m", commit_msg], cwd=embargoed_root)
    try:
        _run(["git", "push"], cwd=embargoed_root)
    except subprocess.CalledProcessError as exc:
        print(f"[oss_fuzz_sweep] WARNING: push failed: {exc}; commit is local")
    return sweep_dir


def sweep_one_project(args: argparse.Namespace) -> int:
    meta = ProjectMeta.fetch(args.project)
    print(f"[oss_fuzz_sweep] project={meta.name} repo={meta.main_repo} lang={meta.language}")

    project_root = clone_or_pull(meta, args.corpus_root)
    prepare_corpus(meta.name, project_root)
    source_dir = discover_sources(project_root)
    print(f"[oss_fuzz_sweep] source-dir: {source_dir}")

    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    artifact_dir = args.artifact_root / meta.name / run_id
    log_path = Path("/home/syc/AProver/findings") / "oss_fuzz" / f"{meta.name}_{run_id}.log"

    extra_env = load_env_file(Path("/home/syc/.config/bmc-agent/env"))
    extra_env.setdefault("BMC_AGENT_K2_NOTE", f"run_id={run_id}")
    # Smuggle per-project exclude globs through extra_env so the
    # run_verify_dir() helper can stitch them into --exclude flags.
    excl = excludes_for(meta.name)
    if excl:
        extra_env["__BMC_AGENT_EXCLUDE_PATS__"] = "|".join(excl)

    if args.corpus_only:
        print("[oss_fuzz_sweep] --corpus-only: skipping verify-dir")
        return 0

    rc = run_verify_dir(
        source_dir, artifact_dir, extra_env, log_path,
        minimal=args.minimal,
        extra_args=args.extra,
    )
    print(f"[oss_fuzz_sweep] verify-dir exit={rc}")

    findings = []
    for src_path, report in iter_bug_reports(artifact_dir):
        if not passes_triage(report):
            continue
        md = render_finding(report, src_path, run_id, meta)
        findings.append((src_path, report, md))
    print(f"[oss_fuzz_sweep] {len(findings)} bug(s) passed triage gate")

    sweep_dir = upload_findings(
        findings, meta, run_id, args.embargoed_root, args.dry_run,
    )
    print(f"[oss_fuzz_sweep] report dir: {sweep_dir}")
    return rc


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--project", required=True, help="OSS-Fuzz project name (e.g. libpng)")
    p.add_argument("--corpus-root", type=Path, default=DEFAULT_CORPUS_ROOT)
    p.add_argument("--artifact-root", type=Path, default=DEFAULT_ARTIFACT_ROOT)
    p.add_argument("--embargoed-root", type=Path, default=DEFAULT_EMBARGOED_ROOT)
    p.add_argument("--dry-run", action="store_true",
                   help="Render reports but don't commit/push to embargoed repo")
    p.add_argument("--corpus-only", action="store_true",
                   help="Clone/sync the project source then stop (smoke test)")
    p.add_argument("--minimal", action="store_true",
                   help="Pass --minimal to verify-dir (disable optional AI layers)")
    p.add_argument("--extra", nargs=argparse.REMAINDER,
                   help="Extra args forwarded to verify-dir verbatim")
    return p


def main() -> int:
    args = build_parser().parse_args()
    return sweep_one_project(args)


if __name__ == "__main__":
    sys.exit(main())
